### PR TITLE
Rodina show time frontend fix

### LINKED ISSUE #324: Add Rodina Féktory show

### PR DESCRIPTION
**Pull request by gammaw**
#324

### CODE REVIEW

File: wp/wp-content/themes/lahma_maker/Showsschedule.php [hunk 1]
```diff
@@ -54,7 +54,7 @@
 <div class="Friday day">
     <h3>Friday / Péntek</h3>
     <ul>
-        <li>15:30-16:00 <strong><a href="../shows/rodina-fektory/">Rodina Féktory</a></strong></li>
```
Comment (gammaw) [inline wp/wp-content/themes/lahma_maker/Showsschedule.php:57]: Silly you
